services:
  matrix-link-replacer:
    image: ghcr.io/aosus/matrix-privacy-link-bot:latest
    container_name: matrix-link-replacer
    restart: unless-stopped
    environment:
      HOMESERVER: https://matrix.aosus.org # Or your homeserver
      USER_ID: "@linkbot:aosus.org" # The bot's Matrix User ID
      PASSWORD: xxxxxxxxxx # The bot's password
      DEVICE_ID: linkmatrixbot # Optional, will be used for the session
#      LOG_LEVEL: DEBUG
    volumes:
      # Mount a directory from the host to persist the Matrix client store.
      # This allows the bot to remember its session (access token, device ID, sync token)
      # across restarts, avoiding the need for password login every time.
      # Ensure MATRIX_BOT_STORE_PATH in your .env file is set to /app/store (or whatever you use here).
      - ./matrix_bot_data/store:/app/store
      #
      # Example for custom config files (optional):
      # If you use custom alts.json/services.json and point to them via env vars like:
      # MATRIX_BOT_ALTS_JSON_PATH=/app/user_config/alts.json
      # MATRIX_BOT_SERVICES_JSON_PATH=/app/user_config/services.json
      # Then you would mount your local config directory like this:
      # - ./my_custom_config:/app/user_config:ro
