name: Docker Build and Publish

on:
  push:
    branches:
      - main # Or your default branch, e.g., master
  pull_request:
    branches:
      - main # Or your default branch

jobs:
  build-and-push-image:
    # Only run this job on pushes to the main branch
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' # Adjust 'main' if your default branch is different
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # Needed to push to GHCR

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}
          tags: |
            type=sha,prefix=sha-
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  build-for-pr:
    # Only run this job on pull requests
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    permissions:
      contents: read # Only need to read the repo content

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image (no push)
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false # Just build, don't push
          # No need for tags or labels here as we are not pushing
          # Optionally, you can load it to docker to run tests if you have them
          # load: true

      # Example of a simple test: check if the bot script can be executed with --help
      # This is a very basic test and might need adjustment based on your bot's CLI
      # - name: Run a basic container health check (example)
      #   if: steps.docker_build.outputs.digest != '' # Only if build succeeded
      #   run: |
      #     docker run --rm ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:${{ github.sha }} python matrix_bot.py --help
      #     # Note: The tag above might not be available if not loaded.
      #     # If using load:true in build step, you can use a simpler image name.
      #     # This step is illustrative; actual testing would depend on the bot's capabilities.
      #     echo "Container build successful. Further runtime tests would go here if applicable."
